### ISSUE TITLE
GitHub lacks any tags after 0.1.39

### ISSUE THREAD

**Issue by andrewshadura** [Eugeny/reconfigure#11]
Please push the tags :)

Thanks!

**Comment by andrewshadura** [comment]
@Eugeny, any news on this?

**Comment by andrewshadura** [comment]
@Eugeny, any updates?

**Comment by jayvdb** [comment]
@Eugeny ping

**Comment by andrewshadura** [comment]
On my side, I gave up waiting a year ago: https://bugs.debian.org/933659

**Comment by Eugeny** [comment]
Hey, as you probably already figured, this project is not being maintained at this time :) - sorry for the long silence. I've just pushed the recent tags and added a few requested fixes.

**Comment by jayvdb** [comment]
Thanks.  Now in openSUSE https://build.opensuse.org/package/show/openSUSE:Factory/python-reconfigure , and being used in cfgdiff build test suite
